### ISSUE TITLE
Error while following instructions of first px4 build

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Devguide#1]
I have a new ubuntu 14.04 LTS system and get an error while following the instructions for the first build of the PX4 firmware.

*make px4fmu-v2_default* gives:

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /home/carl/Wingtra/Standard_PX4/Firmware/build_px4fmu-v2_default/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/carl/Wingtra/Standard_PX4/Firmware/build_px4fmu-v2_default/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_ASM_COMPILER
CMake Error: Could not find cmake module file: /home/carl/Wingtra/Standard_PX4/Firmware/build_px4fmu-v2_default/CMakeFiles/2.8.12.2/CMakeASMCompiler.cmake
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** [px4fmu-v2_default] Error 1

**Comment by LorenzMeier** [comment]
As we test this on CI this is a problem of your local environment. Please do a fresh clone.
