### ISSUE TITLE
Instructions how to build for eagle

### ISSUE THREAD

**Issue by julianoes** [PX4/Devguide#109]
We need instructions how to build the Linux image for the Snapdragon Flight, and how to flash it using fastboot.

**Comment by LorenzMeier** [comment]
@mcharleb @jywilson FYI: We need good instructions in the dev guide so the platform becomes consumable.

**Comment by johnfinley** [comment]
This problem seemed close enough for this issue. In https://github.com/PX4/Devguide/blob/master/book/starting-building.md, down at `make mainapp-load`, there is no makefile there. I manually did the commands in the build.ninja file and it worked; I assume there is a new way to do them via build.ninja, but I don't know what to do with that file. Similar for the `make libmainapp-load`. Otherwise everything worked, starting from absolute zero!

**Comment by liamstask** [comment]
`ninja mainapp-load` and `ninja libmainapp-load` work for these, fwiw

**Comment by julianoes** [comment]
@johnfinley I don't quite get what you mean. Are you saying this command does not work for you?

```
make posix_eagle_default && (cd build_posix_eagle_default && make mainapp-load) && make qurt_eagle_default && (cd build_qurt_eagle_default && make libmainapp-load)
```

**Comment by johnfinley** [comment]
Correct; the "make mainapp-load" does not work because there is no makefile. "ninja mainapp-load" works.

**Comment by mcharleb** [comment]
If you are building with ninja, what you suggest is likely true but not at all true if you are not using ninja.

**Comment by liamstask** [comment]
`make posix_eagle_default` runs cmake with the ninja generator, so with the current instructions, ninja is indeed being used.

**Comment by mcharleb** [comment]
Unless you don't have ninja installed...

**Comment by liamstask** [comment]
the plot thickens!

sounds like adding a note that these commands may differ based on whether ninja is installed would be helpful.

**Comment by julianoes** [comment]
Ok I'm obviously completely ignorant of ninja. So is the build system somehow using ninja if it is available. Is that a feature of cmake or of PX4?

**Comment by liamstask** [comment]
px4, i believe

**Comment by dagar** [comment]
It's a check in the px4 top level Makefile. If you want to try it just install ninja and delete your existing build_* directories.

**Comment by julianoes** [comment]
Thanks @dagar, found it: http://dev.px4.io/starting-installing-linux-boutique.html#ninja-build-system

**Comment by skye-AL** [comment]
Hi all!
A bit off-topic, but fitting this issue _Instructions how to build for eagle_:
With the current aDSP image provided by Intrinsyc, the eagle_default build fails to run on the board. A newer aDSP image needs to be used. Therefore @LorenzMeier , @julianoes , @mcharleb , is it possible to make this image somehow available such that developers don't waste time trying to make it run? I wanted to correct the devguide for that point but didn't know what to say.

**Comment by julianoes** [comment]
This was done a while ago. It's now as easy as `make eagle_default upload`.
