### ISSUE TITLE
Bracketed text hidden by browsers on concept-mixing.md

### ISSUE THREAD

**Issue by eraustud** [PX4/Devguide#149]
@LorenzMeier 
[concept-mixing.md] (https://github.com/PX4/Devguide/blob/master/book/concept-mixing.md "Concept Mixing") has some of its bracketed text hidden by browsers because it is encased in `<angle brackets>` that browsers interpret as HTML tags. This makes it very confusing/impossible to read.

Fixed markdown and submitted pull request. Please let me know if it needs adjustment (first-time contributor).

**Comment by LorenzMeier** [comment]
Thanks for fixing this!
