### ISSUE TITLE
Debugging instructions don't work

### ISSUE THREAD

**Issue by julianoes** [PX4/Devguide#154]
I would like to use gdb to debug SITL, however the instructions http://dev.px4.io/simulation-debugging.html don't seem to work anymore:

```
make posix_sitl_default gazebo_gdb 
Skipping submodules. NUTTX_SRC is set to 
PX4 CONFIG: posix_sitl_default
make[1]: *** No rule to make target 'gazebo_gdb'.  Stop.
Makefile:153: recipe for target 'posix_sitl_default' failed
make: *** [posix_sitl_default] Error 2
```

**Comment by dagar** [comment]
`make posix_sitl_default gazebo___gdb` is what I've been using. It's pretty confusing though.

**Comment by julianoes** [comment]
This has been updated, thanks.
