### ISSUE TITLE
A typo which cause the html error.

### ISSUE THREAD

**Issue by intijk** [PX4/Devguide#161]
in book/simulation-gazebo.md, line 87
```
<aside>
```
This should be 
```
</aside> 
```
to close the tag. 

This problem cause the doc page http://dev.px4.io/simulation-gazebo.html not rendered correctly.

**Comment by LorenzMeier** [comment]
Thanks, fixed in https://github.com/PX4/Devguide/commit/a06b7c2344fec88ff6dc743fcc3fbaa5db16972f. You can actually edit the document and send the edit as a PR right in the dev guide.
