### ISSUE TITLE
Permission to PX4/Devguide.git denied

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Devguide#17]
Tried to push some changes to the devguide and got this back:

remote: Permission to PX4/Devguide.git denied to CarlOlsson.
fatal: unable to access 'https://github.com/PX4/Devguide.git/': The requested URL returned error: 403

Have I done something wrong or do I need to get permission?

**Comment by LorenzMeier** [comment]
You need to fork it and send a pull request, like usual.

**Comment by CarlOlsson** [comment]
Yes I have done that

carl@carl-EliteBook:~/Wingtra/px4devguide/Devguide$ git status
On branch added_jlink_debugger
nothing to commit, working directory clean

carl@carl-EliteBook:~/Wingtra/px4devguide/Devguide$ git push origin added_jlink_debugger 
Username for 'https://github.com': CarlOlsson
Password for 'https://CarlOlsson@github.com': 
remote: Permission to PX4/Devguide.git denied to CarlOlsson.
fatal: unable to access 'https://github.com/PX4/Devguide.git/': The requested URL returned error: 403

**Comment by mhkabir** [comment]
You're trying to push to the original repo.

Set up your remotes to have origin as your fork, and upstream as PX4/Devguide.

**Comment by CarlOlsson** [comment]
Oh sorry! Thanks
