### ISSUE TITLE
USB Device Configuration is missing from Linux toolchain installation

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Devguide#2]
In order to communicate with the Pixhawk I had to follow the instructions for USB device config. here:
https://pixhawk.org/dev/toolchain_installation_lin

I think it should be added to the devguide

**Comment by LorenzMeier** [comment]
Could you just send a PR?

**Comment by CarlOlsson** [comment]
Yes will do so

**Comment by LorenzMeier** [comment]
Ping 8)

**Comment by CarlOlsson** [comment]
Unfortunately [the guide](https://pixhawk.org/dev/toolchain_installation_lin) for the USB configuration is now deleted.
