### ISSUE TITLE
Toolchain Installation Snapdragon Flight

### ISSUE THREAD

**Issue by devbharat** [PX4/Devguide#20]
In the instructions provided in the devguide 

    sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf -y
    tar xf Hexagon.LNX.7.2\ Installer-07210.1.tar
    chmod u+x Hexagon.LLVM_linux_installer_7.2.10.bin
    ./Hexagon.LLVM_linux_installer_7.2.10.bin

It isn't really clear where to get the tar file from.

**Comment by boosfelm** [comment]
i have it, it is uploaded to our drive, technical, resources, snapdragon.
please ping me if anyone else needs the file.

**Comment by devbharat** [comment]
Is it not in public domain ? If not we can add that as a comment in the devguide and close this.

**Comment by boosfelm** [comment]
not public atm, but I don't know wether it is critical. @LorenzMeier shall we provide a dropbox link and close this here?

**Comment by LorenzMeier** [comment]
Its not public, so a TODO would make sense there.

**Comment by boosfelm** [comment]
@devbharat can you please add a TODO to the dev guide and point to yourself if someone needs the binary for now.

**Comment by devbharat** [comment]
Yes

**Comment by Pykercao** [comment]
Hi,boosfelm
I'm a Amateur player of PX4, the same problem I met when I build development environment on Ubuntu.Could you send Hexagon.LNX.7.2 to me?
Best Regards

**Comment by boosfelm** [comment]
@devbharat can you do it? Thanks

**Comment by mcharleb** [comment]
You can request the SDK from https://developer.qualcomm.com/software/hexagon-dsp-sdk/application

**Comment by Pykercao** [comment]
@mcharleb That means I can get Hexagon.LNX.7.2 from https://developer.qualcomm.com/software/hexagon-dsp-sdk/application if I request?

**Comment by Pykercao** [comment]
Does anyone have Hexagon.LNX.7.2 ? Who can send the file to me ? I'm in urgent need of the file.
Best Regards,
Pykercao

**Comment by mcharleb** [comment]
@Pykercao It may take a day or so to get the tools after you fill out the form.

**Comment by rgreid** [comment]
Once we have access to this page: https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools where should we look to get access to 'Hexagon.LNX.7.2\ Installer-07210.1.tar' ?

I have already downloaded 'qualcomm_hexagon_sdk_2_0_eval.bin' however I'm getting strange errors building with Hexagon Tools v6.4.06

**Comment by mcharleb** [comment]
Send me your email  (charlebm@gmail.com) and I'll have someone send you the Hexagon.LNX.7.2\ Installer-07210.1.tar file.

**Comment by mcharleb** [comment]
@rgreid I sent a request for you and cc you on the email.

**Comment by smnogar** [comment]
I am also in need of this file. I would very much appreciate it if someone could send me a link.

**Comment by LorenzMeier** [comment]
The file is available from Intrinsyc. We're working with Qualcomm to get it into the normal SDK tools space. Issue to track this is https://github.com/PX4/Devguide/issues/97

**Comment by joaonatividade** [comment]
Hi guys! I'm still trying to find the "Hexagon.LNX.7.2 Installer-07210.1.tar" file. Can you help me with this? I need it in order to start programming with my PX4.

Thanks in advance,

João Natividade

**Comment by LorenzMeier** [comment]
Please contact @mcharleb.

**Comment by chenbinpeng** [comment]
I have the same problem with Pykercao, Could someone send Hexagon.LNX.7.2 to me? Thanks very much!(cbp@gezhuzi.com)

**Comment by kartikmohta** [comment]
Just to let you know, the `Hexagon SDK v2.0 Add-On for HVX - Linux` download on https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools contains the Hexagon Tools v7.2.10. Just run it as `sh qualcomm_hexagon_sdk_hvx_addon_2_0_eval.bin` and it starts up the installer for the Hexagon Tools.

**Comment by mcharleb** [comment]
Thanks! I'll update the docs.
