### ISSUE TITLE
No instructions for installing libstdc++-arm-none-eabi-newlib

### ISSUE THREAD

**Issue by mcharleb** [PX4/Devguide#21]
There are no C++ header files for the NuttX build unless libstdc++-arm-none-eabi-newlib is installed. I am testing on Ubuntu 15.10.

The following does not work on Ubuntu 15.10:
```
sudo apt-get install gcc-arm-none-eabi=4.8.3-18ubuntu2+12 -y
```
as that version of gcc is not available.

**Comment by LorenzMeier** [comment]
We are not using newlib on NuttX. What is the output for
```
sudo apt-get madison gcc-arm-none-eabi
```

For you?
