### ISSUE TITLE
gazebo sitl build problem following instructions

### ISSUE THREAD

**Issue by gokoreas** [PX4/Devguide#51]
I have been following the instructions in http://dev.px4.io/starting-installing-linux.html

However, I get the following error

I thought maybe it was the error in my CMake but I cannot solve the problem

![screenshot from 2016-01-10 19 47 57](https://cloud.githubusercontent.com/assets/5248102/12221210/b07d092e-b7d3-11e5-9c2b-503b7efb7166.png)

**Comment by andre-nguyen** [comment]
Did you install the entire toolchain? Not having a C compiler sounds fishy...

**Comment by gokoreas** [comment]
I have solved the problem :)

I solved it by reinstalling the tool chain installation

I also had problems uninstalling gazebo 2.3 and installing gazebo 6 in indigo
