### ISSUE TITLE
Add instructions how to add a model in Gazebo and read its output in ROS

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Devguide#94]
We need these:
```roslaunch gazebo_ros empty_world.launch``` and ```rosrun gazebo_ros spawn_model -file iris.sdf -sdf -model iris```

This file as example:
https://github.com/andre-nguyen/sitl_gazebo/commit/0b0c5e09e46030d8780803d7be1999ad9a599e88

@psiorx @andre-nguyen It would be fantastic if you could help out here and get that covered properly in the docs. I had a student trying to do essentially that and he failed.

**Comment by andre-nguyen** [comment]
With regards to adding a sensor to the simulation, I will wait for @psiorx to test out the code I linked him before documenting it.

Its pretty straightforward when you look at the docs in Gazebo, but there's always a bit of fiddling involved.
